---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin/"
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: src/content/home.md
  label: Home
- type: document
  path: src/content/about-us.md
  label: About Us
- type: document
  path: src/content/products.md
  label: Products
- type: document
  path: src/content/contact.md
  label: Contact
- type: heading
  label: Products
- type: directory
  path: src/content/products/croissant/*
  label: Croissant
  create: documents
  match: "**/*"
  templates:
  - product
- type: directory
  path: src/content/products/danish/*
  label: Danish
  create: documents
  match: "**/*"
  templates:
  - product
- type: directory
  path: src/content/products/basic-bread/*
  label: Basic Bread
  create: documents
  match: "**/*"
  templates:
  - product
- type: directory
  path: src/content/products/toast/*
  label: Toast
  create: documents
  match: "**/*"
  templates:
  - product
- type: directory
  path: src/content/products/muffin/*
  label: Muffin
  create: documents
  match: "**/*"
  templates:
  - product
- type: directory
  path: src/content/products/cakes-cookies/*
  label: Cakes & Cookies
  create: documents
  match: "**/*"
  templates:
  - product
- type: directory
  path: src/content/categories
  label: Categories
  create: documents
  match: "**/*"
  templates:
  - category
upload_dir: static/uploads
public_path: "/static/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn forestry:preview
