---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin/"
webhook_url: 
sections:
- type: document
  path: src/content/home-page.md
  label: Home Page
  match: "**/*"
- type: heading
  label: Global
- type: heading
  label: Content
- type: directory
  path: src/content/categories
  label: Categories
  create: documents
  match: "**/*"
  templates:
  - category
- type: directory
  path: src/content/products
  label: Products
  create: documents
  match: "**/*"
  templates:
  - product
upload_dir: static/uploads
public_path: "/static/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn forestry:preview
