---
label: Product
hide_body: true
display_field: name
fields:
- name: name
  type: text
  config:
    required: true
  label: Name
  description: Product Name
- name: category
  type: select
  default: []
  config:
    required: true
    options: []
    source:
      type: pages
      section: categories
      file: 
      path: 
  label: Category
  description: Product Category
- name: thumbnail
  type: file
  config:
    maxSize: 250
  label: Thumbnail
  description: Product Thumbnail
- name: photo
  type: file
  config:
    maxSize: 250
  label: Photo
  hidden: false
  description: Product Photo
- name: alt_photo
  type: file
  config:
    maxSize: 250
  label: Alt Photo
  description: Product Alternative Photo
pages:
- src/content/products/almond-croissant.md
- src/content/products/almond-muffin.md
- src/content/products/apple-danish.md
- src/content/products/apple-muffin.md
- src/content/products/baguette.md
- src/content/products/banana-muffin.md
- src/content/products/black-forest.md
- src/content/products/blueberry-danish.md
- src/content/products/blueberry-muffin.md
- src/content/products/brioche.md
- src/content/products/brown-toast.md
- src/content/products/burger-buns.md
- src/content/products/buttery-oreo.md
- src/content/products/chewy-cheese-marble.md
- src/content/products/chocolate-corissant.md
- src/content/products/chocolate-muffin.md
- src/content/products/ciabatta-basil.md
- src/content/products/ciabatta-plain.md
- src/content/products/dark-rye-bread.md
- src/content/products/english-muffin.md
- src/content/products/focaccia-herb-oregano.md
- src/content/products/focaccia-olive.md
- src/content/products/hot-dog-buns.md
- src/content/products/mix-fruit-muffin.md
- src/content/products/multi-grain-bread.md
- src/content/products/multigrain-toast.md
- src/content/products/multimalt-cereal-mix-bread.md
- src/content/products/nastar.md
- src/content/products/oatmeal-raisin.md
- src/content/products/peach-danish.md
- src/content/products/pitta-bread.md
- src/content/products/plain-croissant.md
- src/content/products/plain-muffin.md
- src/content/products/raisin-roll-danish.md
- src/content/products/rye-toast.md
- src/content/products/snow-white.md
- src/content/products/sourdough.md
- src/content/products/sovital-bread.md
- src/content/products/strawberry-danish.md
- src/content/products/strawberry-muffin.md
- src/content/products/sunflower-sesame-bagel.md
- src/content/products/walnut-raisin-roll.md
- src/content/products/white-dinner-sesame-poppy-seed-roll.md
- src/content/products/white-toast.md
- src/content/products/wholemeal-bread.md
