---
label: Product
hide_body: true
display_field: name
fields:
- name: name
  type: text
  config:
    required: true
  label: Name
  description: Product Name
- name: category
  type: select
  default: []
  config:
    required: true
    options: []
    source:
      type: pages
      section: categories
      file: 
      path: 
  label: Category
  description: Product Category
- name: photo
  type: file
  config:
    maxSize: 250
  label: Photo
  hidden: false
  description: Product Photo
- name: alt_photo
  type: file
  config:
    maxSize: 250
  label: Alt Photo
  description: Product Alternative Photo
pages:
- src/content/products/almond-croissant.md
- src/content/products/apple-danish.md
- src/content/products/baguette.md
- src/content/products/blueberry-danish.md
- src/content/products/burger-buns.md
- src/content/products/chocolate-corissant.md
- src/content/products/peach-danish.md
- src/content/products/plain-croissant.md
- src/content/products/raisin-roll-danish.md
- src/content/products/strawberry-danish.md
